### ISSUE TITLE
Links para la política de cookies

### ISSUE THREAD

**Issue by cr0hn** [onticsoluciones/iuris#3]
Sugerencia para nuevos links:
- /politica-cookies.jsp
- /informacion-sobre-cookies
- /uso-de-cookies
- /politicaCookies.jsp

**Comment by alfonsomoratalla** [comment]
Añadidos nuevos links sugeridos al plugin de Politica de cookies en 4ed0085ad81370844bd61b233e84413f9ab1a396

Gracias
