### ISSUE TITLE
Cloudflare SessionID

### ISSUE THREAD

**Issue by cr0hn** [onticsoluciones/iuris#4]
Sugerencia:

Cloudflare SessionID: *__cfduid*

<img width="791" alt="1__dani_warning-virus-found_____virtualenvs_tmp-9f1bcf339784e146__zsh_" src="https://user-images.githubusercontent.com/4076390/49297688-b0f97400-f4bb-11e8-8c3c-6ac97d30e13d.png">

**Comment by alfonsomoratalla** [comment]
Añadida cookie de sesión de Cloudfare en a80502f185a878cef353d8da0a391df49ecacdd2

Gracias
